"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Plus } from "lucide-react";
import { addMemory } from "@/lib/actions/memories";
import RichTextEditor from "./RichTextEditor";

export default function MemoryComposer({
  defaultDate = "",
}: {
  defaultDate?: string;
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [isPending, setIsPending] = useState(false);
  const [htmlContent, setHtmlContent] = useState("");

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsPending(true);
    const formData = new FormData(e.currentTarget);
    // Append the HTML generated by Tiptap before sending to Supabase
    formData.append("description", htmlContent);

    await addMemory(formData);

    setIsPending(false);
    setIsOpen(false);
    setHtmlContent("");
  };

  return (
    <>
      <button
        onClick={() => setIsOpen(true)}
        className="fixed bottom-8 right-8 w-14 h-14 bg-primary text-background rounded-full flex items-center justify-center shadow-lg hover:scale-105 transition-transform z-40"
      >
        <Plus className="w-6 h-6" />
      </button>

      <AnimatePresence>
        {isOpen && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsOpen(false)}
              className="fixed inset-0 bg-background/80 backdrop-blur-sm z-50"
            />

            <motion.div
              initial={{ x: "100%", opacity: 0 }}
              animate={{ x: 0, opacity: 1 }}
              exit={{ x: "100%", opacity: 0 }}
              transition={{ type: "spring", damping: 25, stiffness: 200 }}
              className="fixed top-0 right-0 w-full max-w-lg h-full bg-background border-l border-border shadow-2xl z-50 p-8 overflow-y-auto"
            >
              <button
                onClick={() => setIsOpen(false)}
                className="absolute top-8 right-8 text-foreground/40 hover:text-primary transition-colors"
              >
                <X className="w-6 h-6" />
              </button>

              <div className="mt-12 mb-8 border-b border-border pb-4">
                <span className="text-primary font-serif text-xs tracking-[0.2em] uppercase">
                  Archive Entry
                </span>
                <h2 className="font-serif text-3xl text-foreground mt-2">
                  New Memory
                </h2>
              </div>

              <form onSubmit={handleSubmit} className="flex flex-col gap-6">
                <div className="flex flex-col gap-2">
                  <label className="text-xs uppercase tracking-widest text-foreground/50 font-serif">
                    Date
                  </label>
                  <input
                    type="date"
                    name="memory_date"
                    defaultValue={defaultDate}
                    required
                    className="p-3 bg-secondary/10 border border-border focus:border-primary/50 outline-none font-serif text-foreground"
                  />
                </div>

                <div className="flex flex-col gap-2">
                  <label className="text-xs uppercase tracking-widest text-foreground/50 font-serif">
                    Title
                  </label>
                  <input
                    type="text"
                    name="title"
                    placeholder="e.g., Coffee at the Corner Shop"
                    required
                    className="p-3 bg-secondary/10 border border-border focus:border-primary/50 outline-none font-serif text-foreground"
                  />
                </div>

                <div className="flex flex-col gap-2">
                  <label className="text-xs uppercase tracking-widest text-foreground/50 font-serif">
                    Story
                  </label>
                  <RichTextEditor onChange={setHtmlContent} />
                </div>

                <button
                  type="submit"
                  disabled={isPending}
                  className="mt-4 py-4 bg-primary text-background font-serif uppercase tracking-[0.2em] text-xs hover:bg-primary/90 transition-colors disabled:opacity-50"
                >
                  {isPending ? "Saving to Archive..." : "Save to Archive"}
                </button>
              </form>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}
